version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8080:8080" # Server port
    networks:
      - app_network

  client:
    build: ./client
    depends_on:
      - server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
